- docs/DeveloperGuide.md
Define use cases and user stories. 
Closes #9.
Co-authored-by: NatalieTanML <nat130613@gmail.com>
Co-authored-by: justinekoh <justinetaikoh@gmail.com>
Co-authored-by: Gnoznaug <zhouguanzong@gmail.com>
Co-authored-by: xMashedxTomatox <xmashedxtomatox@gmail.com>
> Update user guide

- docs/DeveloperGuide.md
Fix developer guide use case indentation.
Closes #9
> Fix developer guide use case indentation

- docs/_config.yml
- docs/_sass/minima/_base.scss
> Rename project in jekyll config

- docs/UserGuide.md
> Update quick start and Add command sections in UG

- docs/UserGuide.md
Updating documentation on list command to the latest intended implementation.
Addresses: #7
> Update list command section in UG

- docs/team/justinekoh.md
> Add Justine's skeletal Project Portfolio Page

- docs/UserGuide.md
> Update save and manual edit sections

- docs/DeveloperGuide.md
- docs/UserGuide.md
- docs/team/chuabingquan.md
- docs/team/gnoznaug.md
- docs/team/justinekoh.md
- docs/team/natalietanml.md
- docs/team/xmashedxtomatox.md
Fixed minor grammatical and formatting errors, removed some terms from glossary, and added the RepoSense links to all our PPPs.
> Update User Guide and Developer Guide

- src/main/java/seedu/address/model/meetingentry/IsRecurring.java
- src/main/java/seedu/address/model/meetingentry/MeetingDateTime.java
- src/main/java/seedu/address/model/meetingentry/MeetingEntry.java
- src/main/java/seedu/address/model/meetingentry/MeetingEntryList.java
- src/main/java/seedu/address/model/meetingentry/MeetingName.java
- src/main/java/seedu/address/model/meetingentry/MeetingUrl.java
- src/main/java/seedu/address/model/meetingentry/NameOrTagsContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/meetingentry/exceptions/DuplicateMeetingEntryException.java
- src/main/java/seedu/address/model/meetingentry/exceptions/MeetingEntryNotFoundException.java
This PR implements the `MeetingEntry` module, along with its associated models.
Closes #35
> Create MeetingEntry module and models

- .github/PULL_REQUEST_TEMPLATE.md
This PR creates a GitHub PR template that will be automatically applied upon creating a PR in the team repo.
> Create GitHub PR template

- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/LinkyTime.java
- src/main/java/seedu/address/model/meetingentry/MeetingEntry.java
- src/main/java/seedu/address/model/meetingentry/MeetingEntryContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/meetingentry/NameOrModuleCodeOrTagsContainsKeywordsPredicate.java
- src/main/java/seedu/address/model/meetingentry/UniqueMeetingEntryList.java
- src/main/java/seedu/address/model/modulecode/ModuleCode.java
- src/main/java/seedu/address/model/modulecode/UniqueModuleCodeList.java
- src/main/java/seedu/address/model/modulecode/exceptions/DuplicateModuleCodeException.java
- src/main/java/seedu/address/model/modulecode/exceptions/ModuleCodeNotFoundException.java
- src/main/java/seedu/address/storage/JsonLinkyTimeStorage.java
Closes #50 
- Adds `ModuleCode` package and related models
- Adds `ModuleCode` as a member in `MeetingEntry`
Up next: Implement GUI to display the module code list (v1.3)
> Implement ModuleCode models

- src/main/java/seedu/address/logic/commands/meetingentry/ListCommand.java
- src/main/java/seedu/address/logic/parser/LinkyTimeParser.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/MeetingEntryCard.java
- src/main/java/seedu/address/ui/MeetingEntryListPanel.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/MeetingEntryCard.fxml
- src/main/resources/view/MeetingListPanel.fxml
- src/test/java/seedu/address/logic/LogicManagerTest.java
Closes #36 
Added the list command case in the switch in LinkyTimeParser
Updated ui model to work with meeting entries instead of person
- Added MeetingEntryCard to replace PersonCard
- Added MeetingEntryListPanel to replace PersonListPanel
- Added relevant FXML files for the new ui model
> Implement command for listing all meeting entries

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/MeetingEntryCard.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
For #61. 
Removed Logic and LogicManager classes dependencies to Address Book's logic.
Removed or altered test cases that depended on Address Book's legacy implementation.
> Decouple AddressBook Logic Dependencies

- src/main/java/seedu/address/logic/commands/meetingentry/AddCommand.java
For #66
Minor fix to follow UG convention of using URL instead of LINK
> Fix usage feedback to show URL instead of LINK to follow UG

- src/test/java/seedu/address/logic/commands/ListCommandTest.java
For #39 and #61
Updated legacy test cases for list command to work with meeting entry list
> Update unit and integration tests for list command

- src/main/java/seedu/address/MainApp.java
> Release v1.2.1

- docs/UserGuide.md
For #73 
Added the meeting duration, with examples.
Fixed the command table as originally it was in a very weird state.
> Update UG with meeting duration and fix the command table format

- src/main/java/seedu/address/model/ModelManager.java
> Update meeting autosort to update every command

- docs/UserGuide.md
> Update user guide to specify that meeting list updates per command

- src/test/java/seedu/address/model/meeting/MeetingContainsAllKeywordsPredicateTest.java
- src/test/java/seedu/address/model/meeting/MeetingContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/model/meeting/MeetingContainsPredicateTest.java
- src/test/java/seedu/address/model/meeting/MeetingNameTest.java
Address #39 Name and contains predicate
> Add test cases for meeting name and the 2 predicates

- src/test/java/seedu/address/logic/commands/meeting/ArchiveMeetingCommandTest.java
- src/test/java/seedu/address/logic/commands/meeting/ListMeetingCommandTest.java
- src/test/java/seedu/address/testutil/meeting/MeetingUtil.java
> Add test cases for list and archive command

- docs/team/natalietanml.md
For #174
Will need to fill out the section on DG contributions after I'm done with that part (in another PR)
> Implement PPP draft

- docs/team/chuabingquan.md
> BQ's PPP Draft

- docs/DeveloperGuide.md
> Add manual testing steps for list, archive and meeting autosort

- docs/DeveloperGuide.md
For #58.
Add `Opening of Meeting Links` and `List and Archive` sections to the appendix segment for notable changes.
> Add open meeting links and list/archive sections to DG

- docs/DeveloperGuide.md
> Add meeting and module model to effort appendix

- docs/DeveloperGuide.md
- docs/SettingUp.md
Format now follows the other sections
> Update manual test format for modules

- docs/team/justinekoh.md
> Docs ppp justine final

- docs/team/gnoznaug.md
> Update gz PPP

- docs/team/xmashedxtomatox.md
> Docs cx finalized ppp
